version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root





      echo "Starting server..."
pwd   # Output the current working directory
ls -l  # List files in the current directory for verification

cd ..

echo "Starting server..."
pwd   # Output the current working directory
ls -l  # List files in the current directory for verification


